services:

  db_0:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soundmatch
    volumes:
      # persist database data so it survives container restarts
      - postgres_data_0:/var/lib/postgresql/data
      # run our init.sql on first startup
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"  # expose on 5433 to avoid clashing with your local postgres

  db_1:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soundmatch
    volumes:
      - postgres_data_1:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  db_2:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soundmatch
    volumes:
      - postgres_data_2:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"

  db_3:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soundmatch
    volumes:
      - postgres_data_3:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5436:5432"

  backend:
    build: ./backend
    environment:
      SHARD_0_URL: postgresql://postgres:postgres@db_0:5432/soundmatch
      SHARD_1_URL: postgresql://postgres:postgres@db_1:5432/soundmatch
      SHARD_2_URL: postgresql://postgres:postgres@db_2:5432/soundmatch
      SHARD_3_URL: postgresql://postgres:postgres@db_3:5432/soundmatch
      REDIS_URL: redis://redis:6379
    volumes:
      - uploads_tmp:/tmp/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db_0
      - db_1
      - db_2
      - db_3
      - redis
    # wait for postgres to be ready before starting
    command: >
      sh -c "sleep 3 && uvicorn main:app --host 0.0.0.0 --port 8000"

  worker:
    build: ./backend
    environment:
      SHARD_0_URL: postgresql://postgres:postgres@db_0:5432/soundmatch
      SHARD_1_URL: postgresql://postgres:postgres@db_1:5432/soundmatch
      SHARD_2_URL: postgresql://postgres:postgres@db_2:5432/soundmatch
      SHARD_3_URL: postgresql://postgres:postgres@db_3:5432/soundmatch
      REDIS_URL: redis://redis:6379
    volumes:
      - uploads_tmp:/tmp/uploads
    depends_on:
      - db_0
      - db_1
      - db_2
      - db_3
      - redis
    command: >
      sh -c "sleep 5 && celery -A tasks worker --loglevel=info --concurrency=2"

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data_0:
  postgres_data_1:
  postgres_data_2:
  postgres_data_3:
  uploads_tmp: